// AUTO-GENERATED by scripts/generate-types.js — do not edit by hand.
// Run `npm run build:types` after changing src/data/gear.json.

export type GearType = 'pedal' | 'amp' | 'cab' | 'rack';

export interface GearInfo {
  company: string;
  model: string;
  type: GearType;
  /** The controls/knobs. Always empty for cabs, which have none. */
  parameter: string[];
}

export declare const GEAR_TYPES: GearType[];

/**
 * Every entry, normalized, as one shared frozen array — allocated once.
 * Use this to index or scan; use `all()` when you need a mutable copy.
 */
export declare const gear: readonly Readonly<GearInfo>[];

/** Pro Co */
export interface ProCoBrand {
  /** RAT2 — pedal */
  rat2(): GearInfo;
}

/** Boss */
export interface BossBrand {
  /** DS-1 — pedal */
  ds1(): GearInfo;
  /** SD-1 — pedal */
  sd1(): GearInfo;
  /** BD-2 — pedal */
  bd2(): GearInfo;
  /** CE-2 — pedal */
  ce2(): GearInfo;
  /** DM-2 — pedal */
  dm2(): GearInfo;
  /** CS-3 — pedal */
  cs3(): GearInfo;
  /** CE-1 — pedal */
  ce1(): GearInfo;
  /** OC-2 — pedal */
  oc2(): GearInfo;
  /** VB-2 — pedal */
  vb2(): GearInfo;
  /** MT-2 — pedal */
  mt2(): GearInfo;
  /** HM-2 — pedal */
  hm2(): GearInfo;
  /** OD-1 — pedal */
  od1(): GearInfo;
  /** CS-1 — pedal */
  cs1(): GearInfo;
  /** PN-2 — pedal */
  pn2(): GearInfo;
  /** CE-2W — pedal */
  ce2w(): GearInfo;
  /** FA-1 FET Amplifier — pedal */
  fa1_fet_amplifier(): GearInfo;
}

/** Ibanez */
export interface IbanezBrand {
  /** TS808 — pedal */
  ts808(): GearInfo;
  /** TS9 — pedal */
  ts9(): GearInfo;
}

/** MXR */
export interface MxrBrand {
  /** Distortion+ — pedal */
  distortionplus(): GearInfo;
  /** Phase 90 — pedal */
  phase_90(): GearInfo;
  /** Dyna Comp — pedal */
  dyna_comp(): GearInfo;
  /** Micro Amp — pedal */
  micro_amp(): GearInfo;
  /** Flanger — pedal */
  flanger(): GearInfo;
}

/** Electro-Harmonix */
export interface ElectroHarmonixBrand {
  /** Big Muff Pi — pedal */
  big_muff_pi(): GearInfo;
  /** Small Stone — pedal */
  small_stone(): GearInfo;
  /** Deluxe Memory Man — pedal */
  deluxe_memory_man(): GearInfo;
  /** Russian Big Muff Pi — pedal */
  russian_big_muff_pi(): GearInfo;
}

/** Klon */
export interface KlonBrand {
  /** Centaur — pedal */
  centaur(): GearInfo;
}

/** Dunlop */
export interface DunlopBrand {
  /** Fuzz Face — pedal */
  fuzz_face(): GearInfo;
  /** Cry Baby — pedal */
  cry_baby(): GearInfo;
  /** Cry Baby From Hell — pedal */
  cry_baby_from_hell(): GearInfo;
  /** 105Q Bass Wah — pedal */
  _105q_bass_wah(): GearInfo;
  /** Cry Baby Clyde McCoy — pedal */
  cry_baby_clyde_mccoy(): GearInfo;
}

/** Way Huge */
export interface WayHugeBrand {
  /** Green Rhino — pedal */
  green_rhino(): GearInfo;
  /** Red Llama — pedal */
  red_llama(): GearInfo;
}

/** Fulltone */
export interface FulltoneBrand {
  /** OCD — pedal */
  ocd(): GearInfo;
  /** Full-Drive 2 — pedal */
  fulldrive_2(): GearInfo;
}

/** Roland */
export interface RolandBrand {
  /** RE-201 Space Echo — pedal */
  re201_space_echo(): GearInfo;
  /** SDD-320 Dimension D — rack */
  sdd320_dimension_d(): GearInfo;
  /** JC-120 — amp */
  jc120(): GearInfo;
  /** JC-120 2x12 — cab */
  jc120_2x12(): GearInfo;
}

/** Maestro */
export interface MaestroBrand {
  /** Echoplex EP-3 — pedal */
  echoplex_ep3(): GearInfo;
  /** FZ-1 Fuzz-Tone — pedal */
  fz1_fuzztone(): GearInfo;
}

/** Binson */
export interface BinsonBrand {
  /** EchoRec — pedal */
  echorec(): GearInfo;
}

/** A/DA */
export interface ADaBrand {
  /** Flanger — pedal */
  flanger(): GearInfo;
}

/** Musitronics */
export interface MusitronicsBrand {
  /** Mu-Tron III — pedal */
  mutron_iii(): GearInfo;
  /** Bi-Phase — pedal */
  biphase(): GearInfo;
}

/** Shin-ei */
export interface ShinEiBrand {
  /** Uni-Vibe — pedal */
  univibe(): GearInfo;
}

/** Vox */
export interface VoxBrand {
  /** V846 — pedal */
  v846(): GearInfo;
  /** V847 — pedal */
  v847(): GearInfo;
  /** Tone Bender — pedal */
  tone_bender(): GearInfo;
  /** AC-30 Top Boost — amp */
  ac30_top_boost(): GearInfo;
  /** AC-15 — amp */
  ac15(): GearInfo;
  /** AC-15 1x12 Blue Alnico — cab */
  ac15_1x12_blue_alnico(): GearInfo;
  /** AC-30 Fawn 2x12 Blue Alnico — cab */
  ac30_fawn_2x12_blue_alnico(): GearInfo;
  /** AC-30TB 2x12 Silver Alnico — cab */
  ac30tb_2x12_silver_alnico(): GearInfo;
  /** AC-30 2x12 Pre-Rola Greenback Pulsonic — cab */
  ac30_2x12_prerola_greenback_pulsonic(): GearInfo;
}

/** Marshall */
export interface MarshallBrand {
  /** Guv'nor — pedal */
  guvnor(): GearInfo;
  /** Bluesbreaker — pedal */
  bluesbreaker(): GearInfo;
  /** Shred Master — pedal */
  shred_master(): GearInfo;
  /** JTM-45 — amp */
  jtm45(): GearInfo;
  /** JTM-50 — amp */
  jtm50(): GearInfo;
  /** Super Lead 100 — amp */
  super_lead_100(): GearInfo;
  /** JCM-800 2203 — amp */
  jcm800_2203(): GearInfo;
  /** JCM-800 2204 — amp */
  jcm800_2204(): GearInfo;
  /** Silver Jubilee 2555 — amp */
  silver_jubilee_2555(): GearInfo;
  /** JCM900 4100 — amp */
  jcm900_4100(): GearInfo;
  /** Super Bass 100 — amp */
  super_bass_100(): GearInfo;
  /** JMP-1 — amp */
  jmp1(): GearInfo;
  /** JVM410HJS — amp */
  jvm410hjs(): GearInfo;
  /** 1933 1x12 Texas Heat — cab */
  _1933_1x12_texas_heat(): GearInfo;
  /** Basketweave 4x12 G12M-20 — cab */
  basketweave_4x12_g12m20(): GearInfo;
  /** Basketweave 4x12 G12M-25 — cab */
  basketweave_4x12_g12m25(): GearInfo;
  /** Basketweave 4x12 G12H-30 — cab */
  basketweave_4x12_g12h30(): GearInfo;
  /** 1935A 4x12 G12M25 — cab */
  _1935a_4x12_g12m25(): GearInfo;
  /** 1935B 4x12 Alnico Cream — cab */
  _1935b_4x12_alnico_cream(): GearInfo;
  /** 1960A 4x12 G12T-75 — cab */
  _1960a_4x12_g12t75(): GearInfo;
  /** 1960A 4x12 G12M25 — cab */
  _1960a_4x12_g12m25(): GearInfo;
  /** 1960A 4x12 G12-50GL Lynchback — cab */
  _1960a_4x12_g1250gl_lynchback(): GearInfo;
  /** 1960AV 4x12 V30 — cab */
  _1960av_4x12_v30(): GearInfo;
  /** 1960B 4x12 Greenback — cab */
  _1960b_4x12_greenback(): GearInfo;
  /** 1960B 4x12 Pulsonic Greenback — cab */
  _1960b_4x12_pulsonic_greenback(): GearInfo;
  /** 1960B 4x12 V30 — cab */
  _1960b_4x12_v30(): GearInfo;
  /** 1960TV 4x12 Celestion — cab */
  _1960tv_4x12_celestion(): GearInfo;
  /** 2551B 4x12 Celestion — cab */
  _2551b_4x12_celestion(): GearInfo;
}

/** Z.Vex */
export interface ZVexBrand {
  /** Fuzz Factory — pedal */
  fuzz_factory(): GearInfo;
}

/** Xotic */
export interface XoticBrand {
  /** EP Booster — pedal */
  ep_booster(): GearInfo;
  /** RC Booster — pedal */
  rc_booster(): GearInfo;
  /** BB Preamp — pedal */
  bb_preamp(): GearInfo;
  /** SP Compressor — pedal */
  sp_compressor(): GearInfo;
  /** AC Booster — pedal */
  ac_booster(): GearInfo;
}

/** Hermida */
export interface HermidaBrand {
  /** Zendrive — pedal */
  zendrive(): GearInfo;
}

/** Analogman */
export interface AnalogmanBrand {
  /** King of Tone — pedal */
  king_of_tone(): GearInfo;
}

/** Tech 21 */
export interface Tech21Brand {
  /** SansAmp Bass Driver DI — pedal */
  sansamp_bass_driver_di(): GearInfo;
}

/** Earthquaker Devices */
export interface EarthquakerDevicesBrand {
  /** Plumes — pedal */
  plumes(): GearInfo;
}

/** Nobels */
export interface NobelsBrand {
  /** ODR-1 — pedal */
  odr1(): GearInfo;
}

/** Paul Cochrane */
export interface PaulCochraneBrand {
  /** Timmy — pedal */
  timmy(): GearInfo;
}

/** Maxon */
export interface MaxonBrand {
  /** SD-9 Sonic Distortion — pedal */
  sd9_sonic_distortion(): GearInfo;
}

/** Dallas */
export interface DallasBrand {
  /** Rangemaster — pedal */
  rangemaster(): GearInfo;
}

/** DOD */
export interface DodBrand {
  /** 250 Overdrive Preamp — pedal */
  _250_overdrive_preamp(): GearInfo;
}

/** Colorsound */
export interface ColorsoundBrand {
  /** Overdriver — pedal */
  overdriver(): GearInfo;
}

/** Chandler */
export interface ChandlerBrand {
  /** Tube Driver — pedal */
  tube_driver(): GearInfo;
}

/** Tycobrahe */
export interface TycobraheBrand {
  /** Octavia — pedal */
  octavia(): GearInfo;
}

/** Darkglass */
export interface DarkglassBrand {
  /** Microtubes B3K — pedal */
  microtubes_b3k(): GearInfo;
  /** DG212N 2x12 Neodymium — cab */
  dg212n_2x12_neodymium(): GearInfo;
  /** D210C 2x10 Ceramic — cab */
  d210c_2x10_ceramic(): GearInfo;
}

/** Friedman */
export interface FriedmanBrand {
  /** BE-OD — pedal */
  beod(): GearInfo;
  /** BE-100 — amp */
  be100(): GearInfo;
  /** Dirty Shirley — amp */
  dirty_shirley(): GearInfo;
  /** Small Box — amp */
  small_box(): GearInfo;
}

/** Horizon Devices */
export interface HorizonDevicesBrand {
  /** Precision Drive — pedal */
  precision_drive(): GearInfo;
}

/** Keeley */
export interface KeeleyBrand {
  /** Red Dirt — pedal */
  red_dirt(): GearInfo;
}

/** Vemuram */
export interface VemuramBrand {
  /** Jan Ray — pedal */
  jan_ray(): GearInfo;
}

/** Ampeg */
export interface AmpegBrand {
  /** Scrambler — pedal */
  scrambler(): GearInfo;
  /** SVT — amp */
  svt(): GearInfo;
  /** B-15NF Portaflex — amp */
  b15nf_portaflex(): GearInfo;
  /** SVT-2 Pro — amp */
  svt2_pro(): GearInfo;
  /** Heritage SVT-CL — amp */
  heritage_svtcl(): GearInfo;
  /** B-15 1x15 — cab */
  b15_1x15(): GearInfo;
  /** SVT-115HE 1x15 — cab */
  svt115he_1x15(): GearInfo;
  /** PR-410HLF 4x10 — cab */
  pr410hlf_4x10(): GearInfo;
  /** B410HE 4x10 — cab */
  b410he_4x10(): GearInfo;
  /** SVT-810AV 8x10 — cab */
  svt810av_8x10(): GearInfo;
  /** SVT-810 8x10 Eminence — cab */
  svt810_8x10_eminence(): GearInfo;
}

/** Digitech */
export interface DigitechBrand {
  /** Whammy — pedal */
  whammy(): GearInfo;
}

/** Moog */
export interface MoogBrand {
  /** Moogerfooger MF-101 — pedal */
  moogerfooger_mf101(): GearInfo;
}

/** Lovepedal */
export interface LovepedalBrand {
  /** Eternity — pedal */
  eternity(): GearInfo;
}

/** Suhr */
export interface SuhrBrand {
  /** Riot — pedal */
  riot(): GearInfo;
  /** Cab 2x12 V-Type — cab */
  cab_2x12_vtype(): GearInfo;
}

/** Teletronix */
export interface TeletronixBrand {
  /** LA-2A — rack */
  la2a(): GearInfo;
}

/** Universal Audio */
export interface UniversalAudioBrand {
  /** 1176 — rack */
  _1176(): GearInfo;
}

/** Fender */
export interface FenderBrand {
  /** Champ — amp */
  champ(): GearInfo;
  /** 5C3 Tweed Deluxe — amp */
  _5c3_tweed_deluxe(): GearInfo;
  /** Bassman — amp */
  bassman(): GearInfo;
  /** Princeton Reverb — amp */
  princeton_reverb(): GearInfo;
  /** Deluxe Reverb — amp */
  deluxe_reverb(): GearInfo;
  /** Super Reverb — amp */
  super_reverb(): GearInfo;
  /** Twin Reverb — amp */
  twin_reverb(): GearInfo;
  /** High Power Tweed Twin 5F8-A — amp */
  high_power_tweed_twin_5f8a(): GearInfo;
  /** Blues Junior — amp */
  blues_junior(): GearInfo;
  /** Tremolux — amp */
  tremolux(): GearInfo;
  /** Princeton — amp */
  princeton(): GearInfo;
  /** 5F2-A Tweed Princeton — amp */
  _5f2a_tweed_princeton(): GearInfo;
  /** Champ 1x8 — cab */
  champ_1x8(): GearInfo;
  /** Princeton Reverb 1x10 — cab */
  princeton_reverb_1x10(): GearInfo;
  /** Princeton 1x10 C1060 — cab */
  princeton_1x10_c1060(): GearInfo;
  /** Princeton 1x10 C10R — cab */
  princeton_1x10_c10r(): GearInfo;
  /** Princeton Brownface 1x10 G10 Alnico Gold — cab */
  princeton_brownface_1x10_g10_alnico_gold(): GearInfo;
  /** 5C3 Tweed Deluxe 1x12 — cab */
  _5c3_tweed_deluxe_1x12(): GearInfo;
  /** Deluxe 1x12 Oxford — cab */
  deluxe_1x12_oxford(): GearInfo;
  /** Deluxe Blackface 1x12 C12K — cab */
  deluxe_blackface_1x12_c12k(): GearInfo;
  /** Deluxe 1x12 GA-SC64 — cab */
  deluxe_1x12_gasc64(): GearInfo;
  /** Deluxe Tweed 1x12 G12Q — cab */
  deluxe_tweed_1x12_g12q(): GearInfo;
  /** Tremolux 2x10 Oxford Alnico — cab */
  tremolux_2x10_oxford_alnico(): GearInfo;
  /** Twin 2x12 C12N — cab */
  twin_2x12_c12n(): GearInfo;
  /** Twin Reverb 2x12 C12K-2 — cab */
  twin_reverb_2x12_c12k2(): GearInfo;
  /** Tweed Twin 2x12 Classic Alnico — cab */
  tweed_twin_2x12_classic_alnico(): GearInfo;
  /** Cab 2x12 A-Type — cab */
  cab_2x12_atype(): GearInfo;
  /** Blonde Bassman 2x12 V30 — cab */
  blonde_bassman_2x12_v30(): GearInfo;
  /** Bassman 4x10 P10R — cab */
  bassman_4x10_p10r(): GearInfo;
  /** Bassman 4x10 P10Q — cab */
  bassman_4x10_p10q(): GearInfo;
  /** Super Reverb 4x10 CTS Alnico — cab */
  super_reverb_4x10_cts_alnico(): GearInfo;
  /** Bassman 2x15 D130 — cab */
  bassman_2x15_d130(): GearInfo;
}

/** Park */
export interface ParkBrand {
  /** 75 — amp */
  _75(): GearInfo;
  /** 75 4x12 G12H-30 — cab */
  _75_4x12_g12h30(): GearInfo;
}

/** Hiwatt */
export interface HiwattBrand {
  /** DR-103 — amp */
  dr103(): GearInfo;
  /** AP 4x12 Fane — cab */
  ap_4x12_fane(): GearInfo;
  /** SE4123 4x12 — cab */
  se4123_4x12(): GearInfo;
}

/** Sunn */
export interface SunnBrand {
  /** Model T — amp */
  model_t(): GearInfo;
  /** Coliseum 300 — amp */
  coliseum_300(): GearInfo;
  /** 4x12 G12T-75 — cab */
  _4x12_g12t75(): GearInfo;
}

/** MESA/Boogie */
export interface MesaBoogieBrand {
  /** Dual Rectifier — amp */
  dual_rectifier(): GearInfo;
  /** Mark IV — amp */
  mark_iv(): GearInfo;
  /** Lone Star — amp */
  lone_star(): GearInfo;
  /** Bass 400+ — amp */
  bass_400plus(): GearInfo;
  /** Trem-O-Verb — amp */
  tremoverb(): GearInfo;
  /** JP-2C — amp */
  jp2c(): GearInfo;
  /** M9 Carbine — amp */
  m9_carbine(): GearInfo;
  /** Mark IIC+ — amp */
  mark_iicplus(): GearInfo;
  /** TriAxis — amp */
  triaxis(): GearInfo;
  /** Subway Blues — amp */
  subway_blues(): GearInfo;
  /** Extension 1x12 EVM12L — cab */
  extension_1x12_evm12l(): GearInfo;
  /** Mark IV Combo 1x12 — cab */
  mark_iv_combo_1x12(): GearInfo;
  /** Rectifier 2x12 Legend V12 — cab */
  rectifier_2x12_legend_v12(): GearInfo;
  /** Rectifier 2x12 V30 — cab */
  rectifier_2x12_v30(): GearInfo;
  /** Custom 4x12 Black Shadow — cab */
  custom_4x12_black_shadow(): GearInfo;
  /** Stiletto 4x12 V30 — cab */
  stiletto_4x12_v30(): GearInfo;
  /** Standard OS Angled 4x12 V30 — cab */
  standard_os_angled_4x12_v30(): GearInfo;
  /** Standard OS Straight 4x12 V30 — cab */
  standard_os_straight_4x12_v30(): GearInfo;
  /** Oversize Angle 2003 4x12 UK V30 — cab */
  oversize_angle_2003_4x12_uk_v30(): GearInfo;
  /** Traditional Angled 4x12 V30 — cab */
  traditional_angled_4x12_v30(): GearInfo;
  /** Traditional Straight 4x12 G12H30 — cab */
  traditional_straight_4x12_g12h30(): GearInfo;
  /** Traditional Straight 4x12 UK V30 — cab */
  traditional_straight_4x12_uk_v30(): GearInfo;
  /** 4FB 4x12 V30 — cab */
  _4fb_4x12_v30(): GearInfo;
  /** 2x15 EV — cab */
  _2x15_ev(): GearInfo;
  /** PowerHouse 6x10 — cab */
  powerhouse_6x10(): GearInfo;
}

/** Soldano */
export interface SoldanoBrand {
  /** SLO-100 — amp */
  slo100(): GearInfo;
  /** X88R — amp */
  x88r(): GearInfo;
  /** 4x12 Eminence 12-5875 — cab */
  _4x12_eminence_125875(): GearInfo;
}

/** Peavey */
export interface PeaveyBrand {
  /** 5150 — amp */
  _5150(): GearInfo;
  /** Invective — amp */
  invective(): GearInfo;
}

/** EVH */
export interface EvhBrand {
  /** 5150III — amp */
  _5150iii(): GearInfo;
  /** Straight 4x12 G12EVH — cab */
  straight_4x12_g12evh(): GearInfo;
}

/** Diezel */
export interface DiezelBrand {
  /** VH4 — amp */
  vh4(): GearInfo;
  /** Herbert — amp */
  herbert(): GearInfo;
  /** Front Loaded 4x12 V30 — cab */
  front_loaded_4x12_v30(): GearInfo;
}

/** Bogner */
export interface BognerBrand {
  /** Ecstasy 101B — amp */
  ecstasy_101b(): GearInfo;
  /** Shiva — amp */
  shiva(): GearInfo;
  /** Überschall — amp */
  uberschall(): GearInfo;
  /** Uberkab 4x12 G12T-75 — cab */
  uberkab_4x12_g12t75(): GearInfo;
  /** Uberkab 4x12 V30 — cab */
  uberkab_4x12_v30(): GearInfo;
}

/** Revv */
export interface RevvBrand {
  /** Generator 120 — amp */
  generator_120(): GearInfo;
}

/** Paul Reed Smith */
export interface PaulReedSmithBrand {
  /** Archon — amp */
  archon(): GearInfo;
}

/** Orange */
export interface OrangeBrand {
  /** Rockerverb 100 MkIII — amp */
  rockerverb_100_mkiii(): GearInfo;
  /** OR80 — amp */
  or80(): GearInfo;
  /** AD200B MK3 — amp */
  ad200b_mk3(): GearInfo;
  /** Tiny Terror — amp */
  tiny_terror(): GearInfo;
  /** Rockerverb 50 MkII — amp */
  rockerverb_50_mkii(): GearInfo;
  /** AD30HTC — amp */
  ad30htc(): GearInfo;
  /** 2x12 V30 — cab */
  _2x12_v30(): GearInfo;
  /** 4x12 Eminence — cab */
  _4x12_eminence(): GearInfo;
  /** PPC412 4x12 V30 — cab */
  ppc412_4x12_v30(): GearInfo;
}

/** Trainwreck Circuits */
export interface TrainwreckCircuitsBrand {
  /** Express — amp */
  express(): GearInfo;
  /** Liverpool — amp */
  liverpool(): GearInfo;
  /** Rocket — amp */
  rocket(): GearInfo;
}

/** Dr Z */
export interface DrZBrand {
  /** Route 66 — amp */
  route_66(): GearInfo;
  /** Maz 38 — amp */
  maz_38(): GearInfo;
  /** Maz 8 — amp */
  maz_8(): GearInfo;
  /** Z Best 2x12 V30 — cab */
  z_best_2x12_v30(): GearInfo;
}

/** Grammatico */
export interface GrammaticoBrand {
  /** LaGrange — amp */
  lagrange(): GearInfo;
  /** GSG100 — amp */
  gsg100(): GearInfo;
  /** LaGrange 1x12 — cab */
  lagrange_1x12(): GearInfo;
}

/** Matchless */
export interface MatchlessBrand {
  /** DC30 — amp */
  dc30(): GearInfo;
  /** Chieftain — amp */
  chieftain(): GearInfo;
  /** DC30 2x12 G12H-30 — cab */
  dc30_2x12_g12h30(): GearInfo;
  /** DC30 2x12 G12M-35 — cab */
  dc30_2x12_g12m35(): GearInfo;
  /** Chieftain 2x12 V30 — cab */
  chieftain_2x12_v30(): GearInfo;
}

/** ENGL */
export interface EnglBrand {
  /** Fireball 100 — amp */
  fireball_100(): GearInfo;
  /** Savage 120 — amp */
  savage_120(): GearInfo;
  /** Powerball — amp */
  powerball(): GearInfo;
  /** XXL 4x12 V30 — cab */
  xxl_4x12_v30(): GearInfo;
}

/** Silvertone */
export interface SilvertoneBrand {
  /** 1484 — amp */
  _1484(): GearInfo;
  /** 1484 2x12 C12Q — cab */
  _1484_2x12_c12q(): GearInfo;
}

/** Supro */
export interface SuproBrand {
  /** S6616 — amp */
  s6616(): GearInfo;
  /** 1964T Dual-Tone — amp */
  _1964t_dualtone(): GearInfo;
  /** S6616 1x6x9 — cab */
  s6616_1x6x9(): GearInfo;
}

/** Gibson */
export interface GibsonBrand {
  /** EH-185 — amp */
  eh185(): GearInfo;
}

/** Aguilar */
export interface AguilarBrand {
  /** Tone Hammer 500 — amp */
  tone_hammer_500(): GearInfo;
}

/** Dumble */
export interface DumbleBrand {
  /** Overdrive Special — amp */
  overdrive_special(): GearInfo;
}

/** Acoustic */
export interface AcousticBrand {
  /** 360 — amp */
  _360(): GearInfo;
}

/** Markbass */
export interface MarkbassBrand {
  /** Little Mark III — amp */
  little_mark_iii(): GearInfo;
}

/** Morgan */
export interface MorganBrand {
  /** SW50 — amp */
  sw50(): GearInfo;
}

/** Naylor */
export interface NaylorBrand {
  /** Duel 38 — amp */
  duel_38(): GearInfo;
}

/** Splawn */
export interface SplawnBrand {
  /** Quick Rod — amp */
  quick_rod(): GearInfo;
  /** Nitro — amp */
  nitro(): GearInfo;
}

/** Fuchs */
export interface FuchsBrand {
  /** Overdrive Supreme — amp */
  overdrive_supreme(): GearInfo;
}

/** Bad Cat */
export interface BadCatBrand {
  /** Hot Cat 30 — amp */
  hot_cat_30(): GearInfo;
}

/** Carr */
export interface CarrBrand {
  /** Rambler — amp */
  rambler(): GearInfo;
}

/** Komet */
export interface KometBrand {
  /** 60 — amp */
  _60(): GearInfo;
  /** Concorde — amp */
  concorde(): GearInfo;
}

/** Swart */
export interface SwartBrand {
  /** Atomic Space Tone — amp */
  atomic_space_tone(): GearInfo;
}

/** Two-Rock */
export interface TwoRockBrand {
  /** Jet 35 — amp */
  jet_35(): GearInfo;
  /** Open Back 2x12 EVM12L — cab */
  open_back_2x12_evm12l(): GearInfo;
  /** Open Back 2x12 G12-65 — cab */
  open_back_2x12_g1265(): GearInfo;
  /** Open Back 2x12 K and M 65 — cab */
  open_back_2x12_k_and_m_65(): GearInfo;
}

/** Carol-Ann */
export interface CarolAnnBrand {
  /** Tucana 3 — amp */
  tucana_3(): GearInfo;
  /** OD2 — amp */
  od2(): GearInfo;
  /** Triptik — amp */
  triptik(): GearInfo;
}

/** Cornford */
export interface CornfordBrand {
  /** MK50 II — amp */
  mk50_ii(): GearInfo;
  /** RK412 4x12 V30 — cab */
  rk412_4x12_v30(): GearInfo;
}

/** Budda */
export interface BuddaBrand {
  /** Twinmaster — amp */
  twinmaster(): GearInfo;
}

/** Fryette */
export interface FryetteBrand {
  /** Deliverance 60 — amp */
  deliverance_60(): GearInfo;
}

/** Cameron */
export interface CameronBrand {
  /** CCV-100 — amp */
  ccv100(): GearInfo;
}

/** Divided by 13 */
export interface DividedBy13Brand {
  /** CJ11 — amp */
  cj11(): GearInfo;
  /** FTR 37 — amp */
  ftr_37(): GearInfo;
}

/** Carvin */
export interface CarvinBrand {
  /** Legacy VL100 — amp */
  legacy_vl100(): GearInfo;
}

/** Paul Ruby */
export interface PaulRubyBrand {
  /** Rocket — amp */
  rocket(): GearInfo;
}

/** Lee Jackson */
export interface LeeJacksonBrand {
  /** Modified 4x12 Governor — cab */
  modified_4x12_governor(): GearInfo;
  /** Modified 4x12 C90 — cab */
  modified_4x12_c90(): GearInfo;
}

/** VHT */
export interface VhtBrand {
  /** FatBottom 4x12 P50 — cab */
  fatbottom_4x12_p50(): GearInfo;
}

/** Zilla */
export interface ZillaBrand {
  /** Mini Modern 1x12 G12H150 Redback — cab */
  mini_modern_1x12_g12h150_redback(): GearInfo;
  /** Cab 2x12 Creamback G12H-75 — cab */
  cab_2x12_creamback_g12h75(): GearInfo;
  /** Fatboy 2x12 Celestion — cab */
  fatboy_2x12_celestion(): GearInfo;
  /** Open 2x12 Classic Lead 80 — cab */
  open_2x12_classic_lead_80(): GearInfo;
  /** Open 2x12 G12-65 — cab */
  open_2x12_g1265(): GearInfo;
  /** Open 2x12 Alnico Gold — cab */
  open_2x12_alnico_gold(): GearInfo;
  /** Custom 4x12 V30 — cab */
  custom_4x12_v30(): GearInfo;
}

/** Epifani */
export interface EpifaniBrand {
  /** Ultralight 1x12 — cab */
  ultralight_1x12(): GearInfo;
}

/** Eden */
export interface EdenBrand {
  /** D410XLT 4x10 — cab */
  d410xlt_4x10(): GearInfo;
}

export declare class GuitarEffector {
  proco: ProCoBrand;
  boss: BossBrand;
  ibanez: IbanezBrand;
  mxr: MxrBrand;
  electroharmonix: ElectroHarmonixBrand;
  klon: KlonBrand;
  dunlop: DunlopBrand;
  wayhuge: WayHugeBrand;
  fulltone: FulltoneBrand;
  roland: RolandBrand;
  maestro: MaestroBrand;
  binson: BinsonBrand;
  ada: ADaBrand;
  musitronics: MusitronicsBrand;
  shinei: ShinEiBrand;
  vox: VoxBrand;
  marshall: MarshallBrand;
  zvex: ZVexBrand;
  xotic: XoticBrand;
  hermida: HermidaBrand;
  analogman: AnalogmanBrand;
  tech21: Tech21Brand;
  earthquakerdevices: EarthquakerDevicesBrand;
  nobels: NobelsBrand;
  paulcochrane: PaulCochraneBrand;
  maxon: MaxonBrand;
  dallas: DallasBrand;
  dod: DodBrand;
  colorsound: ColorsoundBrand;
  chandler: ChandlerBrand;
  tycobrahe: TycobraheBrand;
  darkglass: DarkglassBrand;
  friedman: FriedmanBrand;
  horizondevices: HorizonDevicesBrand;
  keeley: KeeleyBrand;
  vemuram: VemuramBrand;
  ampeg: AmpegBrand;
  digitech: DigitechBrand;
  moog: MoogBrand;
  lovepedal: LovepedalBrand;
  suhr: SuhrBrand;
  teletronix: TeletronixBrand;
  universalaudio: UniversalAudioBrand;
  fender: FenderBrand;
  park: ParkBrand;
  hiwatt: HiwattBrand;
  sunn: SunnBrand;
  mesaboogie: MesaBoogieBrand;
  soldano: SoldanoBrand;
  peavey: PeaveyBrand;
  evh: EvhBrand;
  diezel: DiezelBrand;
  bogner: BognerBrand;
  revv: RevvBrand;
  paulreedsmith: PaulReedSmithBrand;
  orange: OrangeBrand;
  trainwreckcircuits: TrainwreckCircuitsBrand;
  drz: DrZBrand;
  grammatico: GrammaticoBrand;
  matchless: MatchlessBrand;
  engl: EnglBrand;
  silvertone: SilvertoneBrand;
  supro: SuproBrand;
  gibson: GibsonBrand;
  aguilar: AguilarBrand;
  dumble: DumbleBrand;
  acoustic: AcousticBrand;
  markbass: MarkbassBrand;
  morgan: MorganBrand;
  naylor: NaylorBrand;
  splawn: SplawnBrand;
  fuchs: FuchsBrand;
  badcat: BadCatBrand;
  carr: CarrBrand;
  komet: KometBrand;
  swart: SwartBrand;
  tworock: TwoRockBrand;
  carolann: CarolAnnBrand;
  cornford: CornfordBrand;
  budda: BuddaBrand;
  fryette: FryetteBrand;
  cameron: CameronBrand;
  dividedby13: DividedBy13Brand;
  carvin: CarvinBrand;
  paulruby: PaulRubyBrand;
  leejackson: LeeJacksonBrand;
  vht: VhtBrand;
  zilla: ZillaBrand;
  epifani: EpifaniBrand;
  eden: EdenBrand;

  listCompanies(): string[];
  listModels(companyKey: string): string[];
  /** Every piece of gear, or only those of one type when `type` is given. */
  all(type?: GearType): GearInfo[];
}

export default GuitarEffector;
