import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { toCompanyKey, toModelKey, toPascal } from '../src/normalize.js';
import { GEAR_TYPES } from '../src/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const rawGear = JSON.parse(readFileSync(join(root, 'src', 'data', 'gear.json'), 'utf-8'));

/** @type {Map<string, {companyDisplay: string, models: {modelKey: string, modelDisplay: string, type: string}[]}>} */
const brands = new Map();

for (const gear of rawGear) {
  const companyKey = toCompanyKey(gear.company);
  const modelKey = toModelKey(gear.model);

  if (!brands.has(companyKey)) {
    brands.set(companyKey, { companyDisplay: gear.company, models: [] });
  }
  brands.get(companyKey).models.push({ modelKey, modelDisplay: gear.model, type: gear.type });
}

let output = `// AUTO-GENERATED by scripts/generate-types.js — do not edit by hand.
// Run \`npm run build:types\` after changing src/data/gear.json.

export type GearType = ${GEAR_TYPES.map((t) => `'${t}'`).join(' | ')};

export interface GearInfo {
  company: string;
  model: string;
  type: GearType;
  /** The controls/knobs. Always empty for cabs, which have none. */
  parameter: string[];
}

export declare const GEAR_TYPES: GearType[];

/**
 * Every entry, normalized, as one shared frozen array — allocated once.
 * Use this to index or scan; use \`all()\` when you need a mutable copy.
 */
export declare const gear: readonly Readonly<GearInfo>[];

`;

for (const [, { companyDisplay, models }] of brands) {
  output += `/** ${companyDisplay} */\n`;
  output += `export interface ${toPascal(companyDisplay)}Brand {\n`;
  for (const { modelKey, modelDisplay, type } of models) {
    output += `  /** ${modelDisplay} — ${type} */\n`;
    output += `  ${modelKey}(): GearInfo;\n`;
  }
  output += `}\n\n`;
}

output += `export declare class GuitarEffector {\n`;
for (const [companyKey, { companyDisplay }] of brands) {
  output += `  ${companyKey}: ${toPascal(companyDisplay)}Brand;\n`;
}
output += `
  listCompanies(): string[];
  listModels(companyKey: string): string[];
  /** Every piece of gear, or only those of one type when \`type\` is given. */
  all(type?: GearType): GearInfo[];
}

export default GuitarEffector;
`;

writeFileSync(join(root, 'types', 'index.d.ts'), output, 'utf-8');

const counts = rawGear.reduce((acc, gear) => ({ ...acc, [gear.type]: (acc[gear.type] ?? 0) + 1 }), {});
const breakdown = Object.entries(counts)
  .map(([type, count]) => `${count} ${type}${count === 1 ? '' : 's'}`)
  .join(', ');
console.log(`Generated types/index.d.ts — ${brands.size} brands, ${rawGear.length} items (${breakdown}).`);
